name: .NET Core Desktop

on: [push]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: MotionSickness.sln

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: depend
      run: nuget restore

    - name: build
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:TargetFrameworkVersion=v4.8.1

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: output\${{ matrix.configuration }}\MotionSickness.dll
